/*
 * gen_errcodes — C port of upstream src/backend/utils/generate-errcodes.pl.
 *
 * Reads errcodes.txt and emits a header full of
 *     #define ERRCODE_NAME MAKE_SQLSTATE('x','x','x','x','x')
 * lines. The file is included by every libpq translation unit via
 * postgres.h -> utils/elog.h.
 *
 * Build tool — no link-time dependency on libpq.
 *
 * Usage:
 *     gen_errcodes <input errcodes.txt> <output errcodes.h>
 */
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void
die_perror(const char *msg)
{
    perror(msg);
    exit(1);
}

int main(int argc, char **argv)
{
    if (argc != 3) {
        fprintf(stderr, "usage: %s errcodes.txt errcodes.h\n", argv[0]);
        return 1;
    }
    const char *in_path = argv[1];
    const char *out_path = argv[2];

    FILE *in = fopen(in_path, "r");
    if (!in) die_perror(in_path);
    FILE *out = fopen(out_path, "w");
    if (!out) die_perror(out_path);

    fprintf(out, "/* autogenerated from src/backend/utils/errcodes.txt, do not edit */\n");
    fprintf(out, "/* there is deliberately not an #ifndef ERRCODES_H here */\n");

    char buf[1024];
    while (fgets(buf, sizeof buf, in)) {
        size_t len = strlen(buf);
        while (len > 0 && (buf[len - 1] == '\n' || buf[len - 1] == '\r'))
            buf[--len] = '\0';

        const char *p = buf;
        while (*p == ' ' || *p == '\t') p++;
        if (*p == '\0' || *p == '#') continue;

        if (strncmp(p, "Section:", 8) == 0) {
            const char *hdr = p + 8;
            while (*hdr == ' ' || *hdr == '\t') hdr++;
            fprintf(out, "\n/* %s */\n", hdr);
            continue;
        }

        /* Expected: "XXXXX [EWS] errcode_macro ..."  */
        char sqlstate[6];
        char severity;
        char macro[256];
        if (sscanf(p, "%5s %c %255s", sqlstate, &severity, macro) != 3 ||
            strlen(sqlstate) != 5) {
            fprintf(stderr, "%s: unable to parse line: %s\n", argv[0], buf);
            return 1;
        }
        fprintf(out,
                "#define %s MAKE_SQLSTATE('%c','%c','%c','%c','%c')\n",
                macro,
                sqlstate[0], sqlstate[1], sqlstate[2],
                sqlstate[3], sqlstate[4]);
    }

    if (ferror(in))  die_perror(in_path);
    if (fclose(out)) die_perror(out_path);
    fclose(in);
    return 0;
}
