# Maps the current host OS to PostgreSQL's PORTNAME and sets PG_PORTNAME so
# `src/include/port/<PG_PORTNAME>.h` can be copied to `pg_config_os.h`.
if(WIN32 AND NOT CYGWIN AND NOT MSYS)
    set(PG_PORTNAME win32)
elseif(CYGWIN)
    set(PG_PORTNAME cygwin)
elseif(APPLE)
    set(PG_PORTNAME darwin)
elseif(CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
    set(PG_PORTNAME freebsd)
elseif(CMAKE_SYSTEM_NAME STREQUAL "OpenBSD")
    set(PG_PORTNAME openbsd)
elseif(CMAKE_SYSTEM_NAME STREQUAL "NetBSD")
    set(PG_PORTNAME netbsd)
elseif(CMAKE_SYSTEM_NAME STREQUAL "SunOS")
    set(PG_PORTNAME solaris)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(PG_PORTNAME linux)
else()
    message(WARNING "Unrecognized platform '${CMAKE_SYSTEM_NAME}', defaulting to linux port template")
    set(PG_PORTNAME linux)
endif()
message(STATUS "PostgreSQL PORTNAME: ${PG_PORTNAME}")
